package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppoinAddresses generated by hbm2java
 */
@Entity
@Table(name = "appoin_addresses")
public class AppoinAddresses implements java.io.Serializable {

	private Integer id;
	private int appointmentId;
	private String addStreet;
	private String addArea;
	private String addLandmark;
	private String addCity;
	private String addZipcode;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;

	public AppoinAddresses() {
	}

	public AppoinAddresses(int appointmentId) {
		this.appointmentId = appointmentId;
	}

	public AppoinAddresses(int appointmentId, String addStreet, String addArea, String addLandmark, String addCity, String addZipcode, Integer createdBy, Date createdDate,
			Integer updatedBy, Date updatedDate) {
		this.appointmentId = appointmentId;
		this.addStreet = addStreet;
		this.addArea = addArea;
		this.addLandmark = addLandmark;
		this.addCity = addCity;
		this.addZipcode = addZipcode;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "appointment_id", nullable = false)
	public int getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(int appointmentId) {
		this.appointmentId = appointmentId;
	}

	@Column(name = "add_street", length = 250)
	public String getAddStreet() {
		return this.addStreet;
	}

	public void setAddStreet(String addStreet) {
		this.addStreet = addStreet;
	}

	@Column(name = "add_area", length = 250)
	public String getAddArea() {
		return this.addArea;
	}

	public void setAddArea(String addArea) {
		this.addArea = addArea;
	}

	@Column(name = "add_landmark", length = 250)
	public String getAddLandmark() {
		return this.addLandmark;
	}

	public void setAddLandmark(String addLandmark) {
		this.addLandmark = addLandmark;
	}

	@Column(name = "add_city", length = 50)
	public String getAddCity() {
		return this.addCity;
	}

	public void setAddCity(String addCity) {
		this.addCity = addCity;
	}

	@Column(name = "add_zipcode", length = 10)
	public String getAddZipcode() {
		return this.addZipcode;
	}

	public void setAddZipcode(String addZipcode) {
		this.addZipcode = addZipcode;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
