package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CancelReasons generated by hbm2java
 */
@Entity
@Table(name = "cancel_reasons")
public class CancelReasons implements java.io.Serializable {

	private Integer id;
	private String wrapText;
	private String fullText;

	public CancelReasons() {
	}

	public CancelReasons(String wrapText, String fullText) {
		this.wrapText = wrapText;
		this.fullText = fullText;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "wrap_text", nullable = false, length = 65535)
	public String getWrapText() {
		return this.wrapText;
	}

	public void setWrapText(String wrapText) {
		this.wrapText = wrapText;
	}

	@Column(name = "full_text", nullable = false, length = 65535)
	public String getFullText() {
		return this.fullText;
	}

	public void setFullText(String fullText) {
		this.fullText = fullText;
	}

}
