package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmailSmsStatusId generated by hbm2java
 */
@Embeddable
public class EmailSmsStatusId implements java.io.Serializable {

	private int id;
	private Boolean isSmsSend;
	private Boolean isEmailSend;
	private boolean isEditEmailSend;
	private boolean isEditSmsSend;

	public EmailSmsStatusId() {
	}

	public EmailSmsStatusId(int id, boolean isEditEmailSend, boolean isEditSmsSend) {
		this.id = id;
		this.isEditEmailSend = isEditEmailSend;
		this.isEditSmsSend = isEditSmsSend;
	}

	public EmailSmsStatusId(int id, Boolean isSmsSend, Boolean isEmailSend, boolean isEditEmailSend, boolean isEditSmsSend) {
		this.id = id;
		this.isSmsSend = isSmsSend;
		this.isEmailSend = isEmailSend;
		this.isEditEmailSend = isEditEmailSend;
		this.isEditSmsSend = isEditSmsSend;
	}

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "is_sms_send")
	public Boolean getIsSmsSend() {
		return this.isSmsSend;
	}

	public void setIsSmsSend(Boolean isSmsSend) {
		this.isSmsSend = isSmsSend;
	}

	@Column(name = "is_email_send")
	public Boolean getIsEmailSend() {
		return this.isEmailSend;
	}

	public void setIsEmailSend(Boolean isEmailSend) {
		this.isEmailSend = isEmailSend;
	}

	@Column(name = "is_edit_email_send", nullable = false)
	public boolean isIsEditEmailSend() {
		return this.isEditEmailSend;
	}

	public void setIsEditEmailSend(boolean isEditEmailSend) {
		this.isEditEmailSend = isEditEmailSend;
	}

	@Column(name = "is_edit_sms_send", nullable = false)
	public boolean isIsEditSmsSend() {
		return this.isEditSmsSend;
	}

	public void setIsEditSmsSend(boolean isEditSmsSend) {
		this.isEditSmsSend = isEditSmsSend;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmailSmsStatusId))
			return false;
		EmailSmsStatusId castOther = (EmailSmsStatusId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getIsSmsSend() == castOther.getIsSmsSend()) || (this.getIsSmsSend() != null && castOther.getIsSmsSend() != null && this.getIsSmsSend().equals(
						castOther.getIsSmsSend())))
				&& ((this.getIsEmailSend() == castOther.getIsEmailSend()) || (this.getIsEmailSend() != null && castOther.getIsEmailSend() != null && this.getIsEmailSend().equals(
						castOther.getIsEmailSend()))) && (this.isIsEditEmailSend() == castOther.isIsEditEmailSend()) && (this.isIsEditSmsSend() == castOther.isIsEditSmsSend());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getIsSmsSend() == null ? 0 : this.getIsSmsSend().hashCode());
		result = 37 * result + (getIsEmailSend() == null ? 0 : this.getIsEmailSend().hashCode());
		result = 37 * result + (this.isIsEditEmailSend() ? 1 : 0);
		result = 37 * result + (this.isIsEditSmsSend() ? 1 : 0);
		return result;
	}

}
