package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmailSmsStatus generated by hbm2java
 */
@Entity
@Table(name = "email_sms_status",uniqueConstraints = @UniqueConstraint(columnNames = "id"))
public class EmailSmsStatus implements java.io.Serializable {

	private EmailSmsStatusId id;

	public EmailSmsStatus() {
	}

	public EmailSmsStatus(EmailSmsStatusId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", unique = true, nullable = false)),
			@AttributeOverride(name = "isSmsSend", column = @Column(name = "is_sms_send")), @AttributeOverride(name = "isEmailSend", column = @Column(name = "is_email_send")),
			@AttributeOverride(name = "isEditEmailSend", column = @Column(name = "is_edit_email_send", nullable = false)),
			@AttributeOverride(name = "isEditSmsSend", column = @Column(name = "is_edit_sms_send", nullable = false)) })
	public EmailSmsStatusId getId() {
		return this.id;
	}

	public void setId(EmailSmsStatusId id) {
		this.id = id;
	}

}
