package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fb generated by hbm2java
 */
@Entity
@Table(name = "fb")
public class Fb implements java.io.Serializable {

	private Long uid;
	private String fuid;
	private String ffname;
	private String femail;

	public Fb() {
	}

	public Fb(String fuid, String ffname) {
		this.fuid = fuid;
		this.ffname = ffname;
	}

	public Fb(String fuid, String ffname, String femail) {
		this.fuid = fuid;
		this.ffname = ffname;
		this.femail = femail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UID", unique = true, nullable = false)
	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	@Column(name = "Fuid", nullable = false, length = 100)
	public String getFuid() {
		return this.fuid;
	}

	public void setFuid(String fuid) {
		this.fuid = fuid;
	}

	@Column(name = "Ffname", nullable = false, length = 60)
	public String getFfname() {
		return this.ffname;
	}

	public void setFfname(String ffname) {
		this.ffname = ffname;
	}

	@Column(name = "Femail", length = 60)
	public String getFemail() {
		return this.femail;
	}

	public void setFemail(String femail) {
		this.femail = femail;
	}

}
