package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LabActiveDaysStatusId generated by hbm2java
 */
@Embeddable
public class LabActiveDaysStatusId implements java.io.Serializable {

	private int id;
	private int labId;
	private Date date;
	private short year;
	private short month;
	private short day;
	private char isActive;
	private Date createdTime;
	private int createdBy;
	private int updatedBy;
	private Date updatedTime;

	public LabActiveDaysStatusId() {
	}

	public LabActiveDaysStatusId(int id, int labId, Date date, short year, short month, short day, char isActive, Date createdTime, int createdBy, int updatedBy) {
		this.id = id;
		this.labId = labId;
		this.date = date;
		this.year = year;
		this.month = month;
		this.day = day;
		this.isActive = isActive;
		this.createdTime = createdTime;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	public LabActiveDaysStatusId(int id, int labId, Date date, short year, short month, short day, char isActive, Date createdTime, int createdBy, int updatedBy, Date updatedTime) {
		this.id = id;
		this.labId = labId;
		this.date = date;
		this.year = year;
		this.month = month;
		this.day = day;
		this.isActive = isActive;
		this.createdTime = createdTime;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.updatedTime = updatedTime;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "lab_id", nullable = false)
	public int getLabId() {
		return this.labId;
	}

	public void setLabId(int labId) {
		this.labId = labId;
	}

	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "year", nullable = false)
	public short getYear() {
		return this.year;
	}

	public void setYear(short year) {
		this.year = year;
	}

	@Column(name = "month", nullable = false)
	public short getMonth() {
		return this.month;
	}

	public void setMonth(short month) {
		this.month = month;
	}

	@Column(name = "day", nullable = false)
	public short getDay() {
		return this.day;
	}

	public void setDay(short day) {
		this.day = day;
	}

	@Column(name = "is_active", nullable = false, length = 1)
	public char getIsActive() {
		return this.isActive;
	}

	public void setIsActive(char isActive) {
		this.isActive = isActive;
	}

	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", nullable = false)
	public int getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(int updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "updated_time", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LabActiveDaysStatusId))
			return false;
		LabActiveDaysStatusId castOther = (LabActiveDaysStatusId) other;

		return (this.getId() == castOther.getId())
				&& (this.getLabId() == castOther.getLabId())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this.getDate().equals(castOther.getDate())))
				&& (this.getYear() == castOther.getYear())
				&& (this.getMonth() == castOther.getMonth())
				&& (this.getDay() == castOther.getDay())
				&& (this.getIsActive() == castOther.getIsActive())
				&& ((this.getCreatedTime() == castOther.getCreatedTime()) || (this.getCreatedTime() != null && castOther.getCreatedTime() != null && this.getCreatedTime().equals(
						castOther.getCreatedTime())))
				&& (this.getCreatedBy() == castOther.getCreatedBy())
				&& (this.getUpdatedBy() == castOther.getUpdatedBy())
				&& ((this.getUpdatedTime() == castOther.getUpdatedTime()) || (this.getUpdatedTime() != null && castOther.getUpdatedTime() != null && this.getUpdatedTime().equals(
						castOther.getUpdatedTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getLabId();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + this.getYear();
		result = 37 * result + this.getMonth();
		result = 37 * result + this.getDay();
		result = 37 * result + this.getIsActive();
		result = 37 * result + (getCreatedTime() == null ? 0 : this.getCreatedTime().hashCode());
		result = 37 * result + this.getCreatedBy();
		result = 37 * result + this.getUpdatedBy();
		result = 37 * result + (getUpdatedTime() == null ? 0 : this.getUpdatedTime().hashCode());
		return result;
	}

}
