package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LabBlockedSlots generated by hbm2java
 */
@Entity
@Table(name = "lab_blocked_slots")
public class LabBlockedSlots implements java.io.Serializable {

	private Integer id;
	//private int labId;
	private Labs lab;
	private Date date;
	//private int slotId;
	private Slots slots;
	
	public LabBlockedSlots() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/*@Column(name = "lab_id", nullable = false)
	public int getLabId() {
		return this.labId;
	}

	public void setLabId(int labId) {
		this.labId = labId;
	}*/
	
	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	/*@Column(name = "slot_id", nullable = false)
	public int getSlotId() {
		return this.slotId;
	}

	public void setSlotId(int slotId) {
		this.slotId = slotId;
	}*/

	@ManyToOne(cascade = CascadeType.MERGE)
    @JoinColumn(name = "lab_id")
	public Labs getLab() {
		return lab;
	}

	public void setLab(Labs lab) {
		this.lab = lab;
	}

	@ManyToOne(cascade = CascadeType.MERGE)
    @JoinColumn(name = "slot_id")
	public Slots getSlots() {
		return slots;
	}


	public void setSlots(Slots slots) {
		this.slots = slots;
	}

}
