package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LocationWiseLabCharges generated by hbm2java
 */
@Entity
@Table(name = "location_wise_lab_charges")
public class LocationWiseLabCharges implements java.io.Serializable {

	private Integer id;
	private short locationId;
	private short labId;
	private short pickUpCharge;
	private short minChargeAmount;

	public LocationWiseLabCharges() {
	}

	public LocationWiseLabCharges(short locationId, short labId, short pickUpCharge, short minChargeAmount) {
		this.locationId = locationId;
		this.labId = labId;
		this.pickUpCharge = pickUpCharge;
		this.minChargeAmount = minChargeAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "location_id", nullable = false)
	public short getLocationId() {
		return this.locationId;
	}

	public void setLocationId(short locationId) {
		this.locationId = locationId;
	}

	@Column(name = "lab_id", nullable = false)
	public short getLabId() {
		return this.labId;
	}

	public void setLabId(short labId) {
		this.labId = labId;
	}

	@Column(name = "pick_up_charge", nullable = false)
	public short getPickUpCharge() {
		return this.pickUpCharge;
	}

	public void setPickUpCharge(short pickUpCharge) {
		this.pickUpCharge = pickUpCharge;
	}

	@Column(name = "min_charge_amount", nullable = false)
	public short getMinChargeAmount() {
		return this.minChargeAmount;
	}

	public void setMinChargeAmount(short minChargeAmount) {
		this.minChargeAmount = minChargeAmount;
	}

}
