package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AppFileLocations generated by hbm2java
 */
@Entity
@Table(name = "report_config")
public class ReportConfig implements java.io.Serializable {

	private Integer id;
	private String headerRequired;
	private String footerRequired;
	private String signatureName;
	private String signatureDesignation;
	private String signatureFileLocation;
	private String signatureRequired;
	private Integer labId;
	private String invoiceName;
	private String invoiceDesignation;
	private String invoiceSignatureFileLocation;
	private String invoiceSignatureRequired;

	@Column(name = "invoice_name")
	public String getInvoiceName() {
		return invoiceName;
	}


	public void setInvoiceName(String invoiceName) {
		this.invoiceName = invoiceName;
	}

	@Column(name = "invoice_designation")
	public String getInvoiceDesignation() {
		return invoiceDesignation;
	}


	public void setInvoiceDesignation(String invoiceDesignation) {
		this.invoiceDesignation = invoiceDesignation;
	}

	@Column(name = "invoice_signature_file_loc")
	public String getInvoiceSignatureFileLocation() {
		return invoiceSignatureFileLocation;
	}


	public void setInvoiceSignatureFileLocation(String invoiceSignatureFileLocation) {
		this.invoiceSignatureFileLocation = invoiceSignatureFileLocation;
	}

	@Column(name = "invoice_signature_required")
	public String getInvoiceSignatureRequired() {
		return invoiceSignatureRequired;
	}


	public void setInvoiceSignatureRequired(String invoiceSignatureRequired) {
		this.invoiceSignatureRequired = invoiceSignatureRequired;
	}


	public ReportConfig() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "lab_id")
	public Integer getLabId() {
		return labId;
	}

	@Column(name = "header_required")
	public String getHeaderRequired() {
		return headerRequired;
	}


	public void setHeaderRequired(String headerRequired) {
		this.headerRequired = headerRequired;
	}

	@Column(name = "footer_required")
	public String getFooterRequired() {
		return footerRequired;
	}


	public void setFooterRequired(String footerRequired) {
		this.footerRequired = footerRequired;
	}

	@Column(name = "signature_name")
	public String getSignatureName() {
		return signatureName;
	}

	
	public void setSignatureName(String signatureName) {
		this.signatureName = signatureName;
	}

	@Column(name = "signature_designation")
	public String getSignatureDesignation() {
		return signatureDesignation;
	}


	public void setSignatureDesignation(String signatureDesignation) {
		this.signatureDesignation = signatureDesignation;
	}

	@Column(name = "signature_file_loc")
	public String getSignatureFileLocation() {
		return signatureFileLocation;
	}


	public void setSignatureFileLocation(String signatureFileLocation) {
		this.signatureFileLocation = signatureFileLocation;
	}


	public void setLabId(Integer labId) {
		this.labId = labId;
	}


	@Column(name = "signature_required")
	public String getSignatureRequired() {
		return signatureRequired;
	}


	public void setSignatureRequired(String signatureRequired) {
		this.signatureRequired = signatureRequired;
	}

}
