package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Slabs generated by hbm2java
 */
@Entity
@Table(name = "slabs")
public class Slabs implements java.io.Serializable {

	private SlabsId id;

	public Slabs() {
	}

	public Slabs(SlabsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "slabName", column = @Column(name = "slab_name", nullable = false)),
			@AttributeOverride(name = "slabDuration", column = @Column(name = "slab_duration", nullable = false)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "created_by")),
			@AttributeOverride(name = "createdDate", column = @Column(name = "created_date", nullable = false, length = 19)),
			@AttributeOverride(name = "updatedBy", column = @Column(name = "updated_by")),
			@AttributeOverride(name = "updatedDate", column = @Column(name = "updated_date", nullable = false, length = 19)),
			@AttributeOverride(name = "isDeleted", column = @Column(name = "is_deleted")) })
	public SlabsId getId() {
		return this.id;
	}

	public void setId(SlabsId id) {
		this.id = id;
	}

}
