package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SlabsId generated by hbm2java
 */
@Embeddable
public class SlabsId implements java.io.Serializable {

	private int id;
	private String slabName;
	private int slabDuration;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	private Integer isDeleted;

	public SlabsId() {
	}

	public SlabsId(int id, String slabName, int slabDuration, Date createdDate, Date updatedDate) {
		this.id = id;
		this.slabName = slabName;
		this.slabDuration = slabDuration;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public SlabsId(int id, String slabName, int slabDuration, Integer createdBy, Date createdDate, Integer updatedBy, Date updatedDate, Integer isDeleted) {
		this.id = id;
		this.slabName = slabName;
		this.slabDuration = slabDuration;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "slab_name", nullable = false)
	public String getSlabName() {
		return this.slabName;
	}

	public void setSlabName(String slabName) {
		this.slabName = slabName;
	}

	@Column(name = "slab_duration", nullable = false)
	public int getSlabDuration() {
		return this.slabDuration;
	}

	public void setSlabDuration(int slabDuration) {
		this.slabDuration = slabDuration;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SlabsId))
			return false;
		SlabsId castOther = (SlabsId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getSlabName() == castOther.getSlabName()) || (this.getSlabName() != null && castOther.getSlabName() != null && this.getSlabName().equals(
						castOther.getSlabName())))
				&& (this.getSlabDuration() == castOther.getSlabDuration())
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null && castOther.getCreatedBy() != null && this.getCreatedBy().equals(
						castOther.getCreatedBy())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate()) || (this.getCreatedDate() != null && castOther.getCreatedDate() != null && this.getCreatedDate().equals(
						castOther.getCreatedDate())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null && castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(
						castOther.getUpdatedBy())))
				&& ((this.getUpdatedDate() == castOther.getUpdatedDate()) || (this.getUpdatedDate() != null && castOther.getUpdatedDate() != null && this.getUpdatedDate().equals(
						castOther.getUpdatedDate())))
				&& ((this.getIsDeleted() == castOther.getIsDeleted()) || (this.getIsDeleted() != null && castOther.getIsDeleted() != null && this.getIsDeleted().equals(
						castOther.getIsDeleted())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getSlabName() == null ? 0 : this.getSlabName().hashCode());
		result = 37 * result + this.getSlabDuration();
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		result = 37 * result + (getUpdatedDate() == null ? 0 : this.getUpdatedDate().hashCode());
		result = 37 * result + (getIsDeleted() == null ? 0 : this.getIsDeleted().hashCode());
		return result;
	}

}
