package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SlotsId generated by hbm2java
 */
@Embeddable
public class SlotsId implements java.io.Serializable {

	private int id;
	private int slabId;
	private String startTime;
	private String endTime;
	private int orderToDisplay;
	private int labId;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	private Integer isDeleted;

	public SlotsId() {
	}

	public SlotsId(int id, int slabId, String startTime, String endTime, int orderToDisplay, int labId) {
		this.id = id;
		this.slabId = slabId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.orderToDisplay = orderToDisplay;
		this.labId = labId;
	}

	public SlotsId(int id, int slabId, String startTime, String endTime, int orderToDisplay, int labId, Integer createdBy, Date createdDate, Integer updatedBy, Date updatedDate,
			Integer isDeleted) {
		this.id = id;
		this.slabId = slabId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.orderToDisplay = orderToDisplay;
		this.labId = labId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "slab_id", nullable = false)
	public int getSlabId() {
		return this.slabId;
	}

	public void setSlabId(int slabId) {
		this.slabId = slabId;
	}

	@Column(name = "start_time", nullable = false, length = 10)
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_time", nullable = false, length = 10)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Column(name = "order_to_display", nullable = false)
	public int getOrderToDisplay() {
		return this.orderToDisplay;
	}

	public void setOrderToDisplay(int orderToDisplay) {
		this.orderToDisplay = orderToDisplay;
	}

	@Column(name = "lab_id", nullable = false)
	public int getLabId() {
		return this.labId;
	}

	public void setLabId(int labId) {
		this.labId = labId;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SlotsId))
			return false;
		SlotsId castOther = (SlotsId) other;

		return (this.getId() == castOther.getId())
				&& (this.getSlabId() == castOther.getSlabId())
				&& ((this.getStartTime() == castOther.getStartTime()) || (this.getStartTime() != null && castOther.getStartTime() != null && this.getStartTime().equals(
						castOther.getStartTime())))
				&& ((this.getEndTime() == castOther.getEndTime()) || (this.getEndTime() != null && castOther.getEndTime() != null && this.getEndTime().equals(
						castOther.getEndTime())))
				&& (this.getOrderToDisplay() == castOther.getOrderToDisplay())
				&& (this.getLabId() == castOther.getLabId())
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null && castOther.getCreatedBy() != null && this.getCreatedBy().equals(
						castOther.getCreatedBy())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate()) || (this.getCreatedDate() != null && castOther.getCreatedDate() != null && this.getCreatedDate().equals(
						castOther.getCreatedDate())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null && castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(
						castOther.getUpdatedBy())))
				&& ((this.getUpdatedDate() == castOther.getUpdatedDate()) || (this.getUpdatedDate() != null && castOther.getUpdatedDate() != null && this.getUpdatedDate().equals(
						castOther.getUpdatedDate())))
				&& ((this.getIsDeleted() == castOther.getIsDeleted()) || (this.getIsDeleted() != null && castOther.getIsDeleted() != null && this.getIsDeleted().equals(
						castOther.getIsDeleted())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getSlabId();
		result = 37 * result + (getStartTime() == null ? 0 : this.getStartTime().hashCode());
		result = 37 * result + (getEndTime() == null ? 0 : this.getEndTime().hashCode());
		result = 37 * result + this.getOrderToDisplay();
		result = 37 * result + this.getLabId();
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		result = 37 * result + (getUpdatedDate() == null ? 0 : this.getUpdatedDate().hashCode());
		result = 37 * result + (getIsDeleted() == null ? 0 : this.getIsDeleted().hashCode());
		return result;
	}

}
