package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Tests generated by hbm2java
 */
@Entity
@Table(name = "tests")
public class Tests implements java.io.Serializable {

	private Integer id;
	private String testName;
	private TestCategories testCategory;
	private int labId;
	private int testCharge;
	private String testAbvr;
	private short minDays;
	private short deliveryDays;
	private String testSingleShow;
	private String isPackage;
	private String isFastRequired;
	private String shortDesc;
	private String longDesc;
	private int createdBy;
	private Date createdDate;
	private short updatedBy;
	private Date updatedDate;
	private int isDeleted;
	private String remark;
	private Set<TestLabs> testLabs = new HashSet<TestLabs>(0);
	private Set<AppointmentTests> appointmentTests = new HashSet<AppointmentTests>(0);
	private Set<TestFactorsMap> testFactors = new HashSet<TestFactorsMap>(0);

	public Tests() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "test_name", nullable = false)
	public String getTestName() {
		return this.testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

	
	@Column(name = "lab_id", nullable = false)
	public int getLabId() {
		return this.labId;
	}

	public void setLabId(int labId) {
		this.labId = labId;
	}

	@Column(name = "test_charge", nullable = false)
	public int getTestCharge() {
		return this.testCharge;
	}

	public void setTestCharge(int testCharge) {
		this.testCharge = testCharge;
	}

	@Column(name = "test_abvr", nullable = false, length = 50)
	public String getTestAbvr() {
		return this.testAbvr;
	}

	public void setTestAbvr(String testAbvr) {
		this.testAbvr = testAbvr;
	}

	@Column(name = "min_days", nullable = false)
	public short getMinDays() {
		return this.minDays;
	}

	public void setMinDays(short minDays) {
		this.minDays = minDays;
	}

	@Column(name = "delivery_days", nullable = false)
	public short getDeliveryDays() {
		return this.deliveryDays;
	}

	public void setDeliveryDays(short deliveryDays) {
		this.deliveryDays = deliveryDays;
	}

	@Column(name = "test_single_show", nullable = false, length = 1)
	public String getTestSingleShow() {
		return this.testSingleShow;
	}

	public void setTestSingleShow(String testSingleShow) {
		this.testSingleShow = testSingleShow;
	}

	@Column(name = "is_package", nullable = false, length = 1)
	public String getIsPackage() {
		return this.isPackage;
	}

	public void setIsPackage(String isPackage) {
		this.isPackage = isPackage;
	}

	@Column(name = "is_fast_required", nullable = false, length = 1)
	public String getIsFastRequired() {
		return this.isFastRequired;
	}

	public void setIsFastRequired(String isFastRequired) {
		this.isFastRequired = isFastRequired;
	}

	@Column(name = "short_desc", nullable = false, length = 65535)
	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	@Column(name = "long_desc", nullable = false, length = 65535)
	public String getLongDesc() {
		return this.longDesc;
	}

	public void setLongDesc(String longDesc) {
		this.longDesc = longDesc;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public short getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(short updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "is_deleted", nullable = false)
	public int getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(int isDeleted) {
		this.isDeleted = isDeleted;
	}
	
	@OneToMany(mappedBy = "test")
	public Set<TestLabs> getTestLabs() {
		return testLabs;
	}

	public void setTestLabs(Set<TestLabs> testLabs) {
		this.testLabs = testLabs;
	}

	@OneToMany(mappedBy = "tests")
	public Set<AppointmentTests> getAppointmentTests() {
		return appointmentTests;
	}


	public void setAppointmentTests(Set<AppointmentTests> appointmentTests) {
		this.appointmentTests = appointmentTests;
	}

	@ManyToOne(cascade = CascadeType.MERGE)
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "test_cat_id")
	public TestCategories getTestCategory() {
		return testCategory;
	}


	public void setTestCategory(TestCategories testCategory) {
		this.testCategory = testCategory;
	}


	@OneToMany(mappedBy = "test")
	@OrderBy(value = "id ASC")
	public Set<TestFactorsMap> getTestFactors() {
		return testFactors;
	}


	public void setTestFactors(Set<TestFactorsMap> testFactors) {
		this.testFactors = testFactors;
	}


	public String getRemark() {
		return remark;
	}


	public void setRemark(String remark) {
		this.remark = remark;
	}

}
