package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OrderBy;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * TestLabs generated by hbm2java
 */
@Entity
@Table(name = "test_factors_map")
public class TestFactorsMap implements java.io.Serializable, Comparable<TestFactorsMap> {

	private Integer id;
	private Tests test;
	private TestFactors testFactors;
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	@ManyToOne(cascade = CascadeType.MERGE)
	@NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "test_id")
	public Tests getTest() {
		return test;
	}

	public void setTest(Tests test) {
		this.test = test;
	}

	@ManyToOne(cascade = CascadeType.MERGE)
	@NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "factors_id")
	@OrderBy(value = "sequence ASC")
	public TestFactors getTestFactors() {
		return testFactors;
	}

	public void setTestFactors(TestFactors testFactors) {
		this.testFactors = testFactors;
	}
	
	@Override
	public int compareTo(TestFactorsMap o) {
		if(o.getTestFactors() == null || o.getTestFactors().getSequence() == null) {
			return -1;
		}
		if(this.getTestFactors() == null || this.getTestFactors().getSequence() == null) {
			return 1;
		}
		return this.getTestFactors().getSequence() - o.getTestFactors().getSequence();
	}

}
