package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * TestLabs generated by hbm2java
 */
@Entity
@Table(name = "test_labs")
public class TestLabs implements java.io.Serializable {

	private Integer id;
	private Tests test;
	private Labs lab;
	
	private short labPrice;
	private short labDeliveryDays;
	private String labAbbr;

	public TestLabs() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	@Column(name = "lab_price", nullable = false)
	public short getLabPrice() {
		return this.labPrice;
	}

	public void setLabPrice(short labPrice) {
		this.labPrice = labPrice;
	}

	@Column(name = "lab_delivery_days", nullable = false)
	public short getLabDeliveryDays() {
		return this.labDeliveryDays;
	}

	public void setLabDeliveryDays(short labDeliveryDays) {
		this.labDeliveryDays = labDeliveryDays;
	}

	@Column(name = "lab_abbr", nullable = false, length = 20)
	public String getLabAbbr() {
		return this.labAbbr;
	}

	public void setLabAbbr(String labAbbr) {
		this.labAbbr = labAbbr;
	}

	@ManyToOne(cascade = CascadeType.MERGE)
	@NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "test_id")
	public Tests getTest() {
		return test;
	}

	public void setTest(Tests test) {
		this.test = test;
	}

	@ManyToOne(cascade = CascadeType.MERGE)
	@NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "lab_id")
	public Labs getLab() {
		return lab;
	}

	public void setLab(Labs lab) {
		this.lab = lab;
	}

}
