package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * TestPackages generated by hbm2java
 */
@Entity
@Table(name = "test_packages")
public class TestPackages implements java.io.Serializable {

	private Integer id;
	private Tests childTest;
	private Tests parentTest;
	private char isPackage;

	public TestPackages() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "child_test_id")
	public Tests getChildTest() {
		return childTest;
	}


	public void setChildTest(Tests childTest) {
		this.childTest = childTest;
	}


	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "parent_test_id")
	public Tests getParentTest() {
		return parentTest;
	}


	public void setParentTest(Tests parentTest) {
		this.parentTest = parentTest;
	}


	@Column(name = "is_package", nullable = false, length = 1)
	public char getIsPackage() {
		return this.isPackage;
	}

	public void setIsPackage(char isPackage) {
		this.isPackage = isPackage;
	}

}
