package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users1 generated by hbm2java
 */
@Entity
@Table(name = "users1")
public class Users1 implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String salt;
	private String name;
	private Date joined;
	//private int group;
	private Groups group;
	private int labId;
	private Byte active;
	private String verificationCode;
	private Byte updatedBy;
	private Date updatedOn;
	private boolean passwordRecover;
	private Boolean isHpTermsAccepted;

	public Users1() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "salt", length = 32)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "joined", nullable = false, length = 19)
	public Date getJoined() {
		return this.joined;
	}

	public void setJoined(Date joined) {
		this.joined = joined;
	}

	/*@Column(name = "user_group", nullable = false)
	public int getGroup() {
		return this.group;
	}

	public void setGroup(int group) {
		this.group = group;
	}*/

	@Column(name = "lab_id", nullable = false)
	public int getLabId() {
		return this.labId;
	}

	public void setLabId(int labId) {
		this.labId = labId;
	}

	@Column(name = "active")
	public Byte getActive() {
		return this.active;
	}

	public void setActive(Byte active) {
		this.active = active;
	}

	@Column(name = "verification_code", length = 250)
	public String getVerificationCode() {
		return this.verificationCode;
	}

	public void setVerificationCode(String verificationCode) {
		this.verificationCode = verificationCode;
	}

	@Column(name = "updated_by")
	public Byte getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Byte updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "password_recover", nullable = false)
	public boolean isPasswordRecover() {
		return this.passwordRecover;
	}

	public void setPasswordRecover(boolean passwordRecover) {
		this.passwordRecover = passwordRecover;
	}

	@Column(name = "is_hp_terms_accepted")
	public Boolean getIsHpTermsAccepted() {
		return this.isHpTermsAccepted;
	}

	public void setIsHpTermsAccepted(Boolean isHpTermsAccepted) {
		this.isHpTermsAccepted = isHpTermsAccepted;
	}
	
	@OneToOne(cascade = CascadeType.MERGE)
    @JoinColumn(name = "user_group",nullable = true)
	public Groups getGroup() {
		return group;
	}
	
	public void setGroup(Groups group) {
		this.group = group;
	}


}
