package com.rns.healthplease.web.dao.domain;

// Generated 1 May, 2016 3:04:07 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

	private Integer id;
	//private int loginId;
	private String fname;
	private String mname;
	private String lname;
	private String contact;
	private String address;
	private Character gender;
	private String dob;
	private int age;
	private String addStreet;
	private String addArea;
	private String addLandmark;
	private String addCity;
	private String addZipcode;
	private Integer isDeleted;
	private Integer createdBy;
	private String createdDate;
	private Integer updatedBy;
	private String updatedDate;
	private Users1 loginDetails;
	private Set<Appointments> appointments = new HashSet<Appointments>(0);

	public Users() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/*@Column(name = "login_id", nullable = false)
	public int getLoginId() {
		return this.loginId;
	}

	public void setLoginId(int loginId) {
		this.loginId = loginId;
	}*/

	@Column(name = "fname", length = 100)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "mname", nullable = false, length = 100)
	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	@Column(name = "lname", length = 100)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "contact", nullable = false, length = 250)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "dob", nullable = false, length = 200)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "add_street", length = 250)
	public String getAddStreet() {
		return this.addStreet;
	}

	public void setAddStreet(String addStreet) {
		this.addStreet = addStreet;
	}

	@Column(name = "add_area", length = 250)
	public String getAddArea() {
		return this.addArea;
	}

	public void setAddArea(String addArea) {
		this.addArea = addArea;
	}

	@Column(name = "add_landmark", length = 250)
	public String getAddLandmark() {
		return this.addLandmark;
	}

	public void setAddLandmark(String addLandmark) {
		this.addLandmark = addLandmark;
	}

	@Column(name = "add_city", length = 50)
	public String getAddCity() {
		return this.addCity;
	}

	public void setAddCity(String addCity) {
		this.addCity = addCity;
	}

	@Column(name = "add_zipcode", length = 10)
	public String getAddZipcode() {
		return this.addZipcode;
	}

	public void setAddZipcode(String addZipcode) {
		this.addZipcode = addZipcode;
	}

	@Column(name = "is_deleted")
	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_date", length = 250)
	public String getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "updated_date", length = 250)
	public String getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(String updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(mappedBy = "user")
	public Set<Appointments> getAppointments() {
		return appointments;
	}


	public void setAppointments(Set<Appointments> appointments) {
		this.appointments = appointments;
	}


	@OneToOne(cascade = CascadeType.MERGE)
	@JoinColumn(name = "login_id")
	public Users1 getLoginDetails() {
		return loginDetails;
	}


	public void setLoginDetails(Users1 loginDetails) {
		this.loginDetails = loginDetails;
	}

}
